name: Portfolio CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

      - name: Build Docker Image
        run: docker build -t portfolio-joel .

  deploy-simulation:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Simulate Deployment
        run: |
          echo "DÉPLOIEMENT EN COURS SUR LE SERVEUR..."
          echo "docker pull tapajoel16/portfolio-joel:latest"
          echo "docker run -d --name portfolio -p 80:3000 portfolio-joel"
          echo "✅ Status : SUCCÈS"

      - name: Create Git Tag (Success)
        run: |
          echo "Création du tag automatique v1.0.${{ github.run_number }}"